version: "2.2"
dependencies:
  - project: ppawlowski/flowfuse
    dependencies:
      - project: ppawlowski/driver-localfs
  - project: ppawlowski/driver-localfs
    dependencies:
      - project: ppawlowski/nr-launcher
  - project: ppawlowski/nr-launcher
build:
  - project: ppawlowski/flowfuse
    build-command:
      before:
      #   current: String | List of Strings
      #   upstream: String | List of Strings
        downstream: npm list -g --depth=0
      current: |
        echo "flowfuse is current"
        npm ci
        npm run build
      upstream: | 
        echo "flowfuse is Upstream"
        npm ci
        npm link @flowfuse/driver-localfs
        npm run build
      downstream: |
        echo "flowfuse is downstream"
        npm ci
        npm link @flowfuse/driver-localfs
        npm run build
      after:
        current: |
          pwd
          cat package.json
        upstream: |
          npm list -g --depth=0
      #   downstream: String | List of Strings
    # clone: List of Strings
    # skip: true
  - project: ppawlowski/nr-launcher
    build-command:
      current: |
        npm ci 
        npm run test
      upstream:
        npm ci
        npm run test
        npm link
  - project: ppawlowski/driver-localfs
    build-command:
      current: |
        npm ci
        npm link @flowfuse/nr-launcher
        npm link
      upstream: echo "driver-localfs is Upstream"
      downstream: echo "driver-localfs is Downstream"
      after:
        current: |
          pwd
          cat package.json
      #   upstream: String | List of Strings
      #   downstream: String | List of Strings
    # clone: List of Strings
    # skip: true