version: "2.2"
dependencies:
  - project: ppawlowski/flowfuse
    dependencies:
      - project: ppawlowski/driver-localfs
  - project: ppawlowski/driver-localfs
    dependencies:
      - project: ppawlowski/nr-launcher
  - project: ppawlowski/nr-launcher
build:
  - project: ppawlowski/flowfuse
    build-command:
      # before:
      #   current: String | List of Strings
      #   upstream: String | List of Strings
      #   downstream: String | List of Strings
      current: |
        npm install flowfuse/driver-localfs --save
        npm ci
        npm run build
      upstream: echo "flowfuse is Upstream"
      downstream: echo "flowfuse is Downstream"
      after:
        current: |
          pwd
          cat package.json
      #   upstream: String | List of Strings
      #   downstream: String | List of Strings
    # clone: List of Strings
    # skip: true
  - project: ppawlowski/nr-launcher
    build-command:
      current: |
        npm ci 
        npm run test
      upstream:
        npm ci
        npm run test
        npm link
  - project: ppawlowski/driver-localfs
    build-command:
      # before:
      #   current: String | List of Strings
      #   upstream: String | List of Strings
      #   downstream: String | List of Strings
      current: |
        npm link @flowfuse/nr-launcher
        npm ci
        npm run build
      upstream: echo "driver-localfs is Upstream"
      downstream: echo "driver-localfs is Downstream"
      after:
        current: |
          pwd
          cat package.json
      #   upstream: String | List of Strings
      #   downstream: String | List of Strings
    # clone: List of Strings
    # skip: true