name: Build all on PR

on: [pull_request]

permissions:
  contents: read
  packages: write

jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Chain
        id: build-chain
        uses: kiegroup/github-action-build-chain@v3.5.6
        with:
          definition-file: ./.github/dependency-tree.yml
          flow-type: full_downstream
          logger-level: debug
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: k8s-forge
          path: /home/runner/work/driver-localfs/driver-localfs/ppawlowski_flowfuse/k8s-forge.tar
  publish_image:
    runs-on: ubuntu-latest
    needs: build-chain
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: k8s-forge
          path: ./k8s-forge.tar
      - name: debug
        run: |
          pwd
          ls -l
      - name: Load image
        run: docker load -i k8s-forge.tar
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and Push Image
        run: |
          docker tag k8s-forge:build-chain-local ghcr.io/${{ github.repository_owner }}/flowfuse/k8s-forge:${{ github.run_number }}
          docker push ghcr.io/${{ github.repository_owner }}/flowfuse/k8s-forge:${{ github.run_number }}
