name: Build all on PR

on: [pull_request]

permissions:
  contents: read
  packages: write

jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Chain
        id: build-chain
        uses: kiegroup/github-action-build-chain@v3.5.6
        with:
          definition-file: ./.github/dependency-tree.yml
          flow-type: full_downstream
          logger-level: debug
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

